parameters:
  namespace: kuard-test
  target_name: ${_reclass_:name:short}
  kapitan:
    vars:
      target: ${target_name}
    dependencies:
    - type: git
      source: https://github.com/kapicorp/generators.git
      ref: main
      subdir: lib/
      output_path: lib/
    - type: git
      source: https://github.com/kapicorp/generators.git
      ref: main
      subdir: kubernetes
      output_path: system/generators/kubernetes

    compile:
    - output_path: manifests
      input_type: kadet
      output_type: yml
      input_paths:
        - system/generators/kubernetes

  generators:
    kubernetes:
      namespace:
        name:
          name: ${namespace}
    manifest:
      default_config:
        namespace: ${namespace}
        type: deployment
        service_account:
          create: false
        annotations:
          "manifests.kapicorp.com/generated": "true"
  components:
    kuard:
      image:  gcr.io/kuar-demo/kuard-amd64:1
      ports:
        myhttp:
          service_port: 80
          container_port: 8080

      pull_policy: Always
      security_context:
        runAsNonRoot: true
        runAsUser: 65534
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      service:
        type: ClusterIP

  # configures the ingress generator
  ingresses:
    kuard:
      annotations:
        "cert-manager.io/issuer": "letsencrypt-staging"
      host: kuard.rubenlaguna.com
      tls:
        - hosts:
            - kuard.rubenlaguna.com
          secretName: quickstart-example-tls
      paths:
        - backend:
            service:
              name: kuard
              port:
                number: 80
          path: /
          pathType: Prefix
