apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: kuard-demo-dev
  name: kuard-demo-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kapicorp.dev/component: aaa
    name: aaa
  name: aaa
  namespace: kuard-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aaa
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aaa
    spec:
      containers:
        - image: jmalloc/echo-server
          imagePullPolicy: IfNotPresent
          name: aaa
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
